language: c
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
sudo: true
env:
  global:
  - PINS="crowbar:https://github.com/stedolan/crowbar.git"
  matrix:
  - PACKAGE="optint" OCAML_VERSION=4.07 OPAM_SWITCH=4.07.0 TESTS=true
  - PACKAGE="optint" OCAML_VERSION=4.08 OPAM_SWITCH=4.08.0 TESTS=true
  - PACKAGE="optint" OCAML_VERSION=4.09 OPAM_SWITCH=4.09.0 TESTS=true
  - PACKAGE="optint" OCAML_VERSION=4.10 OPAM_SWITCH=4.10.0 TESTS=true
